---
- hosts: lb
  connection: local
  gather_facts: true
  vars_files:
    - vars/f5_vars.yml
  roles:
    - roles/F5-Roles/block_my_ip
    - roles/F5-Roles/waf_export_policy
    - roles/F5-Roles/waf_block_ip
    - roles/F5-Roles/waf_import_apply_policy

