---
- name: GRAB F5 FACTS
  hosts: f5
  connection: local
  gather_facts: false

  tasks:
    - name: COLLECT BIG-IP FACTS
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - system-info
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          no_f5_teem: true
          validate_certs: false
      register: device_facts

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      ansible.builtin.debug:
        var: device_facts

    - name: DISPLAY ONLY THE MAC ADDRESS
      ansible.builtin.debug:
        var: device_facts['system_info']['base_mac_address']

    - name: DISPLAY ONLY THE VERSION
      ansible.builtin.debug:
        var: device_facts['system_info']['product_version']
