---
- name: BIG-IP TEARDOWN
  hosts: lb
  connection: local
  gather_facts: false
  vars:
    irules: ['irule1', 'irule2']

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          no_f5_teem: yes
          validate_certs: false

    - name: DELETE VIRTUAL SERVER
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{ provider }}"
        name: "vip"
        state: absent

    - name: DELETE POOL
      f5networks.f5_modules.bigip_pool:
        provider: "{{ provider }}"
        name: "http_pool"
        state: absent

    - name: DELETE NODES
      f5networks.f5_modules.bigip_node:
        provider: "{{ provider }}"
        name: "{{ hostvars[item].inventory_hostname }}"
        state: absent
      loop: "{{ groups['web'] }}"

    - name: Delete iRules
      f5networks.f5_modules.bigip_irule:
        provider: "{{ provider }}"
        module: "ltm"
        name: "{{ item }}"
        state: absent
      with_items: "{{ irules }}"
